//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Military.Database
{
    using System;
    
    public enum EEmployeeType : int
    {
        MilitaryStaff = 0,
        SupportStaff = 1
    }
}
