//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Military.Database
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class Employee
    {
        public string JMBG { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public EEmployeeType EmployeeType { get; set; }
        public bool IsDeleted { get; set; }
    }
}
