//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Military.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Examination
    {
        public int Id { get; set; }
        public System.DateTime DateOfExam { get; set; }
    
        public virtual Soldier Soldier { get; set; }
        public virtual Medic Medic { get; set; }
        public virtual Camp Camp { get; set; }
    }
}
